package sk.janobono.wiwa.model;

public enum OrderFormat {
    CSV_NUMBER, CSV_BASIC, CSV_FRAME, CSV_DUPLICATED_BASIC, CSV_DUPLICATED_FRAME, CSV_EDGE, CSV_CORNER_STRAIGHT, CSV_CORNER_ROUNDED,
    PDF_TITLE, PDF_ORDER_NUMBER, PDF_INTEGER, PDF_UNIT, PDF_PRICE, PDF_EDGE, PDF_CORNER_STRAIGHT, PDF_CORNER_ROUNDED
}
