services:
  pg:
    image: public.ecr.aws/docker/library/postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - pg-data:/var/lib/postgresql/data

  smtp:
    image: maildev/maildev:latest
    ports:
      - "8081:1080"

  wiwa-service:
    image: sk.janobono.wiwa/wiwa-service:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Bratislava
      - DB_URL=jdbc:postgresql://pg:5432/app
      - MAIL_HOST=smtp
      - MAIL_PORT=1025
      - INIT_DATA_PATH=./data
      - REFRESH_TOKEN_EXPIRES_IN=120
      - TOKEN_EXPIRES_IN=60
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - smtp

volumes:
  pg-data:
